// updated 16/12/2021

const fallback = {
  "12 Gauge Shot": [
    {
      name: "5.25mm Buckshot",
      damage: "37",
      penValue: "1",
      armorDamage: "15",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: '8.5mm Buckshot "Magnum"',
      damage: "50",
      penValue: "2",
      armorDamage: "26",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: '6.5mm Buckshot "Express"',
      damage: "35",
      penValue: "3",
      armorDamage: "26",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
    },
    {
      name: "7mm Buckshot",
      damage: "39",
      penValue: "3",
      armorDamage: "26",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: "Flechette",
      damage: "25",
      penValue: "31",
      armorDamage: "26",
      fragChange: "0%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "5",
      class6: "5",
      note: "8 Darts, the armor damage is pretty high per dart and with 8 total darts, it destroys armor very quickly. Because it has less than 20 pen, even though it has a 100% fragment chance, it can't fragment. This is true of all ammo under 20 pen",
    },
  ],
  "12 Gauge Slugs": [
    {
      name: "RIP Slug",
      damage: "265",
      penValue: "2",
      armorDamage: "11",
      fragChange: "100%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Superformance HP Slug",
      damage: "220",
      penValue: "5",
      armorDamage: "12",
      fragChange: "39%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Grizzly 40 Slug",
      damage: "190",
      penValue: "12",
      armorDamage: "48",
      fragChange: "12%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Copper Sabot Premier HP",
      damage: "206",
      penValue: "14",
      armorDamage: "46",
      fragChange: "38%",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Lead Slug",
      damage: "167",
      penValue: "15",
      armorDamage: "55",
      fragChange: "20%",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Dual Sabot Slug",
      damage: "85",
      penValue: "17",
      armorDamage: "65",
      fragChange: "10%",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "2 Slugs",
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "140",
      penValue: "17",
      armorDamage: "40",
      fragChange: "20%",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "FTX Custom Lite Slug",
      damage: "183",
      penValue: "20",
      armorDamage: "50",
      fragChange: "10%",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "150",
      penValue: "20",
      armorDamage: "50",
      fragChange: "15%",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Shell With .50 BMG (Tracer)",
      damage: "197",
      penValue: "26",
      armorDamage: "57",
      fragChange: "5%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
    },
    {
      name: "AP 20 Slug",
      damage: "164",
      penValue: "37",
      armorDamage: "65",
      fragChange: "3%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
    },
  ],
  "20 Gauge": [
    {
      name: "5.6mm Buckshot",
      damage: "26",
      penValue: "1",
      armorDamage: "12",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: "6.2mm Buckshot",
      damage: "22",
      penValue: "2",
      armorDamage: "13",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: "7.5mm Buckshot",
      damage: "25",
      penValue: "3",
      armorDamage: "14",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: "7.3mm Buckshot",
      damage: "23",
      penValue: "3",
      armorDamage: "13",
      fragChange: "0%",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
    },
    {
      name: "Devastator Slug",
      damage: "198",
      penValue: "5",
      armorDamage: "13",
      fragChange: "100%",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "120",
      penValue: "14",
      armorDamage: "35",
      fragChange: "20%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Star Slug",
      damage: "154",
      penValue: "16",
      armorDamage: "42",
      fragChange: "10%",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "135",
      penValue: "17",
      armorDamage: "40",
      fragChange: "15%",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
  ],
  "23x75 mm": [
    {
      name: '"Star" Flashbang Slug',
      damage: "0",
      penValue: "0",
      armorDamage: "0",
      fragChange: "20%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Shrapnel 25",
      damage: "78",
      penValue: "10",
      armorDamage: "20",
      fragChange: "0%",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: "Shrapnel 10",
      damage: "87",
      penValue: "11",
      armorDamage: "20",
      fragChange: "0%",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
    },
    {
      name: '"Barricade" Slug',
      damage: "192",
      penValue: "39",
      armorDamage: "75",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "4",
    },
  ],
  "9x18mm": [
    {
      name: "SP8",
      damage: "67",
      penValue: "1",
      armorDamage: "2",
      fragChange: "60%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "SP7",
      damage: "77",
      penValue: "2",
      armorDamage: "5",
      fragChange: "2%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PSV",
      damage: "69",
      penValue: "3",
      armorDamage: "5",
      fragChange: "40%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "P gzh",
      damage: "50",
      penValue: "5",
      armorDamage: "16",
      fragChange: "25%",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PSO gzh",
      damage: "54",
      penValue: "5",
      armorDamage: "13",
      fragChange: "35%",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PS gs PPO",
      damage: "55",
      penValue: "6",
      armorDamage: "16",
      fragChange: "25%",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PRS gs",
      damage: "58",
      penValue: "6",
      armorDamage: "16",
      fragChange: "30%",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PPE gzh",
      damage: "61",
      penValue: "7",
      armorDamage: "15",
      fragChange: "35%",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PPT gzh",
      damage: "59",
      penValue: "8",
      armorDamage: "22",
      fragChange: "17%",
      class1: "5",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PST gzh",
      damage: "50",
      penValue: "12",
      armorDamage: "26",
      fragChange: "20%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "RG028 gzh",
      damage: "65",
      penValue: "13",
      armorDamage: "26",
      fragChange: "2%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "BZT gzh",
      damage: "53",
      penValue: "18",
      armorDamage: "28",
      fragChange: "17%",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PMM",
      damage: "58",
      penValue: "24",
      armorDamage: "33",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PBM",
      damage: "40",
      penValue: "28",
      armorDamage: "30",
      fragChange: "16%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "1",
      class5: "0",
      class6: "0",
    },
  ],
  "7.62x25mm": [
    {
      name: "LRNPC",
      damage: "66",
      penValue: "7",
      armorDamage: "27",
      fragChange: "35%",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "LRN",
      damage: "64",
      penValue: "8",
      armorDamage: "28",
      fragChange: "35%",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "FMJ43",
      damage: "60",
      penValue: "11",
      armorDamage: "29",
      fragChange: "25%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "akbs",
      damage: "58",
      penValue: "12",
      armorDamage: "32",
      fragChange: "25%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "P Gl",
      damage: "58",
      penValue: "14",
      armorDamage: "32",
      fragChange: "25%",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "T Gzh (Tracer)",
      damage: "55",
      penValue: "18",
      armorDamage: "34",
      fragChange: "17%",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Pst gzh",
      damage: "50",
      penValue: "25",
      armorDamage: "36",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
    },
  ],
  "9x19mm": [
    {
      name: "RIP",
      damage: "102",
      penValue: "2",
      armorDamage: "11",
      fragChange: "100%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Quakemaker",
      damage: "85",
      penValue: "8",
      armorDamage: "22",
      fragChange: "10%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PSO gzh",
      damage: "59",
      penValue: "10",
      armorDamage: "32",
      fragChange: "25%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Luger CCI",
      damage: "70",
      penValue: "10",
      armorDamage: "38",
      fragChange: "25%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "T Gzh (Tracer)",
      damage: "58",
      penValue: "14",
      armorDamage: "33",
      fragChange: "15%",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "blue Tracer",
    },
    {
      name: "PST gzh",
      damage: "54",
      penValue: "20",
      armorDamage: "33",
      fragChange: "15%",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "AP 6.3",
      damage: "52",
      penValue: "30",
      armorDamage: "48",
      fragChange: "5%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "1",
    },
    {
      name: "PBP",
      damage: "52",
      penValue: "39",
      armorDamage: "53",
      fragChange: "5%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously 7n31",
    },
  ],
  ".45": [
    {
      name: "RIP",
      damage: "137",
      penValue: "3",
      armorDamage: "12",
      fragChange: "100%",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Hydroshok",
      damage: "105",
      penValue: "13",
      armorDamage: "30",
      fragChange: "50%",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Lasermatch (Tracer)",
      damage: "80",
      penValue: "19",
      armorDamage: "37",
      fragChange: "1%",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "ACP FMJ",
      damage: "76",
      penValue: "25",
      armorDamage: "36",
      fragChange: "1%",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "ACP AP",
      damage: "70",
      penValue: "38",
      armorDamage: "48",
      fragChange: "1%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
    },
  ],
  "9x21mm": [
    {
      name: "PE Gzh",
      damage: "80",
      penValue: "15",
      armorDamage: "63",
      fragChange: "35%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-12",
    },
    {
      name: "P Gzh",
      damage: "65",
      penValue: "18",
      armorDamage: "44",
      fragChange: "30%",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-11",
    },
    {
      name: "PS Gzh",
      damage: "49",
      penValue: "35",
      armorDamage: "46",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      note: "",
      secondNote: "Previously SP-10",
    },
    {
      name: "BT (Tracer)",
      damage: "63",
      penValue: "39",
      armorDamage: "47",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously SP-13",
    },
  ],
  "5.7x28 mm": [
    {
      name: "r37f",
      damage: "98",
      penValue: "8",
      armorDamage: "7",
      fragChange: "100%",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "ss198lf",
      damage: "74",
      penValue: "10",
      armorDamage: "15",
      fragChange: "80%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "r37x",
      damage: "81",
      penValue: "11",
      armorDamage: "14",
      fragChange: "70%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "ss197sr",
      damage: "62",
      penValue: "20",
      armorDamage: "22",
      fragChange: "50%",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "l191 (Tracer)",
      damage: "58",
      penValue: "33",
      armorDamage: "41",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "2",
      class6: "2",
    },
    {
      name: "sb193",
      damage: "54",
      penValue: "35",
      armorDamage: "37",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
    },
    {
      name: "ss190",
      damage: "49",
      penValue: "37",
      armorDamage: "43",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
    },
  ],
  "4.6x30 mm": [
    {
      name: "Action SX",
      damage: "65",
      penValue: "18",
      armorDamage: "39",
      fragChange: "50%",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Subsonic SX",
      damage: "45",
      penValue: "36",
      armorDamage: "46",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "3",
      class6: "2",
    },
    {
      name: "FMJ SX",
      damage: "43",
      penValue: "40",
      armorDamage: "41",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
    },
    {
      name: "AP SX",
      damage: "35",
      penValue: "53",
      armorDamage: "46",
      fragChange: "10%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
  ],
  "9x39mm": [
    {
      name: "SP5",
      damage: "68",
      penValue: "38",
      armorDamage: "52",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
    },
    {
      name: "SP6",
      damage: "58",
      penValue: "46",
      armorDamage: "60",
      fragChange: "10%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
    {
      name: "PAB9",
      damage: "62",
      penValue: "48",
      armorDamage: "72",
      fragChange: "10%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
    {
      name: "SPP",
      damage: "64",
      penValue: "50",
      armorDamage: "56",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
    {
      name: "BP",
      damage: "60",
      penValue: "55",
      armorDamage: "68",
      fragChange: "10%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
  ],
  ".366": [
    {
      name: "Geksa",
      damage: "110",
      penValue: "14",
      armorDamage: "38",
      fragChange: "45%",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "FMJ",
      damage: "98",
      penValue: "23",
      armorDamage: "48",
      fragChange: "25%",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "EKO",
      damage: "73",
      penValue: "30",
      armorDamage: "40",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
    },
    {
      name: "AP",
      damage: "90",
      penValue: "42",
      armorDamage: "60",
      fragChange: "1%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
  ],
  "5.45x39 mm": [
    {
      name: "SP",
      damage: "68",
      penValue: "11",
      armorDamage: "34",
      fragChange: "45%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "HP",
      damage: "74",
      penValue: "11",
      armorDamage: "20",
      fragChange: "35%",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PRS",
      damage: "60",
      penValue: "14",
      armorDamage: "28",
      fragChange: "30%",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "US",
      damage: "65",
      penValue: "15",
      armorDamage: "34",
      fragChange: "10%",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "T (Tracer)",
      damage: "57",
      penValue: "20",
      armorDamage: "38",
      fragChange: "16%",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "FMJ",
      damage: "56",
      penValue: "21",
      armorDamage: "30",
      fragChange: "25%",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "PS",
      damage: "50",
      penValue: "27",
      armorDamage: "35",
      fragChange: "40%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "0",
      class6: "0",
    },
    {
      name: "PP",
      damage: "48",
      penValue: "33",
      armorDamage: "32",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "0",
    },
    {
      name: "BP",
      damage: "49",
      penValue: "35",
      armorDamage: "41",
      fragChange: "16%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "1",
    },
    {
      name: "BT (Tracer)",
      damage: "44",
      penValue: "37",
      armorDamage: "49",
      fragChange: "16%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
    },
    {
      name: "7n40",
      damage: "52",
      penValue: "44",
      armorDamage: "50",
      fragChange: "2%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
    {
      name: "BS",
      damage: "40",
      penValue: "51",
      armorDamage: "57",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
    {
      name: 'PPBS "Igolnik"',
      damage: "37",
      penValue: "62",
      armorDamage: "60",
      fragChange: "2%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
  ],
  "5.56x45 mm": [
    {
      name: "Warmageddon",
      damage: "85",
      penValue: "3",
      armorDamage: "14",
      fragChange: "90%",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "HP",
      damage: "75",
      penValue: "9",
      armorDamage: "22",
      fragChange: "70%",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "MK 255 Mod 0",
      damage: "60",
      penValue: "17",
      armorDamage: "32",
      fragChange: "3%",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "Mk318 SOST",
      damage: "67",
      penValue: "20",
      armorDamage: "35",
      fragChange: "15%",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "M856 (Tracer)",
      damage: "55",
      penValue: "23",
      armorDamage: "34",
      fragChange: "33%",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "FMJ",
      damage: "52",
      penValue: "24",
      armorDamage: "33",
      fragChange: "50%",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "M855",
      damage: "50",
      penValue: "28",
      armorDamage: "37",
      fragChange: "40%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
    },
    {
      name: "M856A1 (Tracer)",
      damage: "51",
      penValue: "37",
      armorDamage: "52",
      fragChange: "33%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
    },
    {
      name: "M855A1",
      damage: "46",
      penValue: "45",
      armorDamage: "52",
      fragChange: "34%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
    {
      name: "M995",
      damage: "40",
      penValue: "53",
      armorDamage: "58",
      fragChange: "32%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
    {
      name: "SSA AP",
      damage: "36",
      penValue: "56",
      armorDamage: "64",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
  ],
  "7.62x39 mm": [
    {
      name: "HP",
      damage: "87",
      penValue: "15",
      armorDamage: "35",
      fragChange: "26%",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "US",
      damage: "56",
      penValue: "29",
      armorDamage: "42",
      fragChange: "8%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
    },
    {
      name: "T45M1",
      damage: "62",
      penValue: "30",
      armorDamage: "46",
      fragChange: "12%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
    },
    {
      name: "PS",
      damage: "57",
      penValue: "32",
      armorDamage: "52",
      fragChange: "25%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
    },
    {
      name: "BP",
      damage: "58",
      penValue: "47",
      armorDamage: "63",
      fragChange: "12%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
    {
      name: "MAI AP",
      damage: "47",
      penValue: "58",
      armorDamage: "76",
      fragChange: "5%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
    },
  ],
  ".300 blk": [
    {
      name: "Whisper",
      damage: "90",
      penValue: "14",
      armorDamage: "18",
      fragChange: "35%",
      class1: "6",
      class2: "4",
      class3: "2",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "VMAX",
      damage: "72",
      penValue: "20",
      armorDamage: "25",
      fragChange: "25%",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "3",
      class5: "1",
      class6: "0",
    },
    {
      name: "BCP FMJ",
      damage: "60",
      penValue: "28",
      armorDamage: "36",
      fragChange: "30%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
    },
    {
      name: "M62 (Tracer)",
      damage: "54",
      penValue: "34",
      armorDamage: "40",
      fragChange: "0.2",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
    },
    {
      name: "AP",
      damage: "55",
      penValue: "44",
      armorDamage: "60",
      fragChange: "30%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
  ],
  "7.62x51 mm": [
    {
      name: "Ultra Nosler",
      damage: "107",
      penValue: "15",
      armorDamage: "20",
      fragChange: "70%",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "FMJ",
      damage: "88",
      penValue: "31",
      armorDamage: "33",
      fragChange: "25%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "2",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously BPZ",
    },
    {
      name: "SP",
      damage: "60",
      penValue: "36",
      armorDamage: "40",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "2",
      class6: "0",
      note: "",
      secondNote: "Previously TPZ",
    },
    {
      name: "M80",
      damage: "80",
      penValue: "41",
      armorDamage: "66",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
    {
      name: "M62 (Tracer)",
      damage: "79",
      penValue: "44",
      armorDamage: "75",
      fragChange: "14%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
    },
    {
      name: "M61",
      damage: "70",
      penValue: "64",
      armorDamage: "83",
      fragChange: "13%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
    {
      name: "M993",
      damage: "67",
      penValue: "70",
      armorDamage: "85",
      fragChange: "13%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
  ],
  "7.62x54R": [
    {
      name: "T-46M (Tracer)",
      damage: "82",
      penValue: "41",
      armorDamage: "83",
      fragChange: "18%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
    },
    {
      name: "LPS Gzh",
      damage: "81",
      penValue: "42",
      armorDamage: "78",
      fragChange: "18%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
    },
    {
      name: "PS",
      damage: "86",
      penValue: "45",
      armorDamage: "84",
      fragChange: "8%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      note: "",
      secondNote: "Previously 7n1",
    },
    {
      name: "BT (Tracer)",
      damage: "78",
      penValue: "59",
      armorDamage: "87",
      fragChange: "8%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7BT1",
    },
    {
      name: "SNB",
      damage: "75",
      penValue: "62",
      armorDamage: "87",
      fragChange: "8%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
    {
      name: "BS",
      damage: "72",
      penValue: "70",
      armorDamage: "88",
      fragChange: "8%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7n37",
    },
  ],
  "12.7x55 mm": [
    {
      name: "ps12a",
      damage: "165",
      penValue: "10",
      armorDamage: "22",
      fragChange: "70%",
      class1: "6",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
    },
    {
      name: "ps12",
      damage: "115",
      penValue: "28",
      armorDamage: "60",
      fragChange: "30%",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "1",
      class6: "0",
    },
    {
      name: "ps12b",
      damage: "102",
      penValue: "46",
      armorDamage: "57",
      fragChange: "30%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
    },
  ],
  ".338 Lapua Magnum": [
    {
      name: "Tac-X",
      damage: "196",
      penValue: "18",
      armorDamage: "55",
      fragChange: "50%",
      class1: "6",
      class2: "5",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
    },
    {
      name: "UPZ",
      damage: "142",
      penValue: "32",
      armorDamage: "70",
      fragChange: "60%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
    },
    {
      name: "FMJ",
      damage: "122",
      penValue: "47",
      armorDamage: "83",
      fragChange: "20%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
    },
    {
      name: "AP",
      damage: "115",
      penValue: "79",
      armorDamage: "89",
      fragChange: "13%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
  ],
  "Mounted Weapons": [
    {
      name: "30mm Grenade",
      damage: "199",
      penValue: "1",
      armorDamage: "95",
      fragChange: "0%",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "This has an explosion radius like grenades which does most (all) of the damage",
    },
    {
      name: "12.7x108mm",
      damage: "182",
      penValue: "88",
      armorDamage: "88",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
    {
      name: "12.7x108mm Tracer",
      damage: "199",
      penValue: "80",
      armorDamage: "95",
      fragChange: "17%",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
    },
  ],
  Other: [
    {
      name: "40mm Buckshot Grenade",
      damage: "160",
      penValue: "5",
      armorDamage: "95",
      fragChange: "0%",
      class1: "5",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "15 Pellets",
    },
  ],
};

export default fallback;
