// updated 16/12/2021

const fallback = {
  "12 Gauge Shot": [
    {
      name: "5.25mm Buckshot",
      damage: "37",
      penValue: "1",
      fragChange: "0%",
      recoil: "",
      effDist: "108",
      maxHsDist: "9",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
    },
    {
      name: '8.5mm Buckshot "Magnum"',
      damage: "50",
      penValue: "2",
      fragChange: "0%",
      recoil: "155",
      effDist: "80",
      maxHsDist: "116",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
    },
    {
      name: '6.5mm Buckshot "Express"',
      damage: "35",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "71",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
      category: "12 Gauge Shot",
    },
    {
      name: "7mm Buckshot",
      damage: "39",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "39",
      maxHsDist: "3",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
    },
    {
      name: "Flechette",
      damage: "25",
      penValue: "31",
      fragChange: "0%",
      recoil: "",
      effDist: "1185",
      maxHsDist: "Never",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "5",
      class6: "5",
      note: "8 Darts, the armor damage is pretty high per dart and with 8 total darts, it destroys armor very quickly",
      category: "12 Gauge Shot",
    },
  ],
  "12 Gauge Slugs": [
    {
      name: "RIP Slug",
      damage: "265",
      penValue: "2",
      fragChange: "100%",
      recoil: "35",
      effDist: "188",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "Because it has less than 20 pen, even though it has a 100% fragment chance, it can't fragment",
      category: "12 Gauge Slugs",
    },
    {
      name: "Superformance HP Slug",
      damage: "220",
      penValue: "5",
      fragChange: "39%",
      recoil: "-15",
      effDist: "344",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "^ This is true of all ammo under 20 pen",
      category: "12 Gauge Slugs",
    },
    {
      name: "Grizzly 40 Slug",
      damage: "190",
      penValue: "12",
      fragChange: "12%",
      recoil: "20",
      effDist: "840",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "Copper Sabot Premier HP",
      damage: "206",
      penValue: "14",
      fragChange: "38%",
      recoil: "10",
      effDist: "305",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "Lead Slug",
      damage: "167",
      penValue: "15",
      fragChange: "20%",
      recoil: "",
      effDist: "487",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "Dual Sabot Slug",
      damage: "85",
      penValue: "17",
      fragChange: "10%",
      recoil: "15",
      effDist: "251",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "2 Slugs",
      category: "12 Gauge Slugs",
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "140",
      penValue: "17",
      fragChange: "20%",
      recoil: "-15",
      effDist: "406",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "FTX Custom Lite Slug",
      damage: "183",
      penValue: "20",
      fragChange: "10%",
      recoil: "-25",
      effDist: "498",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "150",
      penValue: "20",
      fragChange: "15%",
      recoil: "-10",
      effDist: "181",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "Shell With .50 BMG (Tracer)",
      damage: "197",
      penValue: "26",
      fragChange: "5%",
      recoil: "25",
      effDist: "2058",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "12 Gauge Slugs",
    },
    {
      name: "AP 20 Slug",
      damage: "164",
      penValue: "37",
      fragChange: "3%",
      recoil: "50",
      effDist: "905",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "12 Gauge Slugs",
    },
  ],
  "20 Gauge": [
    {
      name: "5.6mm Buckshot",
      damage: "26",
      penValue: "1",
      fragChange: "0%",
      recoil: "10",
      effDist: "124",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
    },
    {
      name: "6.2mm Buckshot",
      damage: "22",
      penValue: "2",
      fragChange: "0%",
      recoil: "",
      effDist: "100",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
    },
    {
      name: "7.5mm Buckshot",
      damage: "25",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "181",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
    },
    {
      name: "7.3mm Buckshot",
      damage: "23",
      penValue: "3",
      fragChange: "0%",
      recoil: "15",
      effDist: "86",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
      category: "20 Gauge",
    },
    {
      name: "Devastator Slug",
      damage: "198",
      penValue: "5",
      fragChange: "100%",
      recoil: "30",
      effDist: "109",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "120",
      penValue: "14",
      fragChange: "20%",
      recoil: "-15",
      effDist: "517",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
    },
    {
      name: "Star Slug",
      damage: "154",
      penValue: "16",
      fragChange: "10%",
      recoil: "5",
      effDist: "416",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "135",
      penValue: "17",
      fragChange: "15%",
      recoil: "-10",
      effDist: "438",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
    },
  ],
  "23x75 mm": [
    {
      name: '"Star" Flashbang Slug',
      damage: "0",
      penValue: "0",
      fragChange: "20%",
      recoil: "",
      effDist: "",
      maxHsDist: "",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "23x75 mm",
    },
    {
      name: "Shrapnel 25",
      damage: "78",
      penValue: "10",
      fragChange: "0%",
      recoil: "10",
      effDist: "83",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "23x75 mm",
    },
    {
      name: "Shrapnel 10",
      damage: "87",
      penValue: "11",
      fragChange: "0%",
      recoil: "",
      effDist: "106",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "23x75 mm",
    },
    {
      name: '"Barricade" Slug',
      damage: "192",
      penValue: "39",
      fragChange: "20%",
      recoil: "25",
      effDist: "974",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "4",
      category: "23x75 mm",
    },
  ],
  "9x18mm": [
    {
      name: "SP8",
      damage: "67",
      penValue: "1",
      fragChange: "60%",
      recoil: "",
      effDist: "412",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "SP7",
      damage: "77",
      penValue: "2",
      fragChange: "2%",
      recoil: "",
      effDist: "229",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PSV",
      damage: "69",
      penValue: "3",
      fragChange: "40%",
      recoil: "",
      effDist: "606",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "P gzh",
      damage: "50",
      penValue: "5",
      fragChange: "25%",
      recoil: "",
      effDist: "478",
      maxHsDist: "638",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PSO gzh",
      damage: "54",
      penValue: "5",
      fragChange: "35%",
      recoil: "",
      effDist: "459",
      maxHsDist: "818",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PS gs PPO",
      damage: "55",
      penValue: "6",
      fragChange: "25%",
      recoil: "",
      effDist: "467",
      maxHsDist: "905",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PRS gs",
      damage: "58",
      penValue: "6",
      fragChange: "30%",
      recoil: "",
      effDist: "478",
      maxHsDist: ">1KM",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PPE gzh",
      damage: "61",
      penValue: "7",
      fragChange: "35%",
      recoil: "",
      effDist: "438",
      maxHsDist: ">1KM",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PPT gzh",
      damage: "59",
      penValue: "8",
      fragChange: "17%",
      recoil: "-7",
      effDist: "495",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PST gzh",
      damage: "50",
      penValue: "12",
      fragChange: "20%",
      recoil: "",
      effDist: "462",
      maxHsDist: "615",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "RG028 gzh",
      damage: "65",
      penValue: "13",
      fragChange: "2%",
      recoil: "",
      effDist: "476",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "BZT gzh",
      damage: "53",
      penValue: "18",
      fragChange: "17%",
      recoil: "",
      effDist: "303",
      maxHsDist: "511",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PMM",
      damage: "58",
      penValue: "24",
      fragChange: "17%",
      recoil: "5",
      effDist: "322",
      maxHsDist: "919",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
    },
    {
      name: "PBM",
      damage: "40",
      penValue: "28",
      fragChange: "16%",
      recoil: "4",
      effDist: "133",
      maxHsDist: "26",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "1",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "290",
      category: "9x18mm",
    },
  ],
  "7.62x25mm": [
    {
      name: "LRNPC",
      damage: "66",
      penValue: "7",
      fragChange: "35%",
      recoil: "-10",
      effDist: "457",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "725",
      category: "7.62x25mm",
    },
    {
      name: "LRN",
      damage: "64",
      penValue: "8",
      fragChange: "35%",
      recoil: "-5",
      effDist: "579",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "575",
      category: "7.62x25mm",
    },
    {
      name: "FMJ43",
      damage: "60",
      penValue: "11",
      fragChange: "25%",
      recoil: "",
      effDist: "175",
      maxHsDist: "595",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "441",
      category: "7.62x25mm",
    },
    {
      name: "akbs",
      damage: "58",
      penValue: "12",
      fragChange: "25%",
      recoil: "-15",
      effDist: "419",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "428",
      category: "7.62x25mm",
    },
    {
      name: "P Gl",
      damage: "58",
      penValue: "14",
      fragChange: "25%",
      recoil: "",
      effDist: "411",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "194",
      category: "7.62x25mm",
    },
    {
      name: "T Gzh (Tracer)",
      damage: "55",
      penValue: "18",
      fragChange: "17%",
      recoil: "",
      effDist: "426",
      maxHsDist: "966",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "453",
      category: "7.62x25mm",
    },
    {
      name: "Pst gzh",
      damage: "50",
      penValue: "25",
      fragChange: "20%",
      recoil: "",
      effDist: "408",
      maxHsDist: "615",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "92",
      category: "7.62x25mm",
    },
  ],
  "9x19mm": [
    {
      name: "RIP",
      damage: "102",
      penValue: "2",
      fragChange: "100%",
      recoil: "20",
      effDist: "290",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
    },
    {
      name: "Quakemaker",
      damage: "85",
      penValue: "8",
      fragChange: "10%",
      recoil: "10",
      effDist: "725",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
    },
    {
      name: "PSO gzh",
      damage: "59",
      penValue: "10",
      fragChange: "25%",
      recoil: "",
      effDist: "575",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
    },
    {
      name: "Luger CCI",
      damage: "70",
      penValue: "10",
      fragChange: "25%",
      recoil: "",
      effDist: "441",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
    },
    {
      name: "T Gzh (Tracer)",
      damage: "58",
      penValue: "14",
      fragChange: "15%",
      recoil: "-6",
      effDist: "428",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Green Tracer",
      category: "9x19mm",
    },
    {
      name: "PST gzh",
      damage: "54",
      penValue: "20",
      fragChange: "15%",
      recoil: "",
      effDist: "194",
      maxHsDist: "452",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
    },
    {
      name: "AP 6.3",
      damage: "52",
      penValue: "30",
      fragChange: "5%",
      recoil: "",
      effDist: "453",
      maxHsDist: "776",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "1",
      category: "9x19mm",
    },
    {
      name: "PBP",
      damage: "52",
      penValue: "39",
      fragChange: "5%",
      recoil: "15",
      effDist: "92",
      maxHsDist: "220",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously 7n31",
      category: "9x19mm",
    },
  ],
  ".45": [
    {
      name: "RIP",
      damage: "137",
      penValue: "3",
      fragChange: "100%",
      recoil: "",
      effDist: "290",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
    },
    {
      name: "Hydroshok",
      damage: "105",
      penValue: "13",
      fragChange: "50%",
      recoil: "",
      effDist: "725",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
    },
    {
      name: "Lasermatch (Tracer)",
      damage: "80",
      penValue: "19",
      fragChange: "1%",
      recoil: "",
      effDist: "575",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
    },
    {
      name: "ACP FMJ",
      damage: "76",
      penValue: "25",
      fragChange: "1%",
      recoil: "",
      effDist: "441",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".45",
    },
    {
      name: "ACP AP",
      damage: "70",
      penValue: "38",
      fragChange: "1%",
      recoil: "7",
      effDist: "428",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".45",
    },
  ],
  "9x21mm": [
    {
      name: "PE Gzh",
      damage: "80",
      penValue: "15",
      fragChange: "35%",
      recoil: "",
      effDist: "194",
      maxHsDist: "452",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-12",
      category: "9x21mm",
    },
    {
      name: "P Gzh",
      damage: "65",
      penValue: "18",
      fragChange: "30%",
      recoil: "",
      effDist: "453",
      maxHsDist: "776",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-11",
      category: "9x21mm",
    },
    {
      name: "PS Gzh",
      damage: "49",
      penValue: "35",
      fragChange: "20%",
      recoil: "",
      effDist: "92",
      maxHsDist: "220",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      note: "",
      secondNote: "Previously SP-10",
      category: "9x21mm",
    },
    {
      name: "BT (Tracer)",
      damage: "63",
      penValue: "39",
      fragChange: "20%",
      recoil: "-4",
      effDist: "292",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously SP-13",
      category: "9x21mm",
    },
  ],
  "5.7x28 mm": [
    {
      name: "r37f",
      damage: "98",
      penValue: "8",
      fragChange: "100%",
      recoil: "",
      effDist: "100",
      maxHsDist: ">1KM",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
    },
    {
      name: "ss198lf",
      damage: "74",
      penValue: "10",
      fragChange: "80%",
      recoil: "",
      effDist: "326",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
    },
    {
      name: "r37x",
      damage: "81",
      penValue: "11",
      fragChange: "70%",
      recoil: "",
      effDist: "100",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
    },
    {
      name: "ss197sr",
      damage: "62",
      penValue: "20",
      fragChange: "50%",
      recoil: "",
      effDist: "401",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
    },
    {
      name: "l191 (Tracer)",
      damage: "58",
      penValue: "33",
      fragChange: "20%",
      recoil: "",
      effDist: "358",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "2",
      class6: "2",
      category: "5.7x28 mm",
    },
    {
      name: "sb193",
      damage: "54",
      penValue: "35",
      fragChange: "20%",
      recoil: "-24",
      effDist: "1113",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      category: "5.7x28 mm",
    },
    {
      name: "ss190",
      damage: "49",
      penValue: "37",
      fragChange: "20%",
      recoil: "",
      effDist: "325",
      maxHsDist: "463",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.7x28 mm",
    },
  ],
  "4.6x30 mm": [
    {
      name: "Action SX",
      damage: "65",
      penValue: "18",
      fragChange: "50%",
      recoil: "",
      effDist: "245",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "4.6x30 mm",
    },
    {
      name: "Subsonic SX",
      damage: "45",
      penValue: "36",
      fragChange: "20%",
      recoil: "-22",
      effDist: "2119",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "3",
      class6: "2",
      category: "4.6x30 mm",
    },
    {
      name: "FMJ SX",
      damage: "43",
      penValue: "40",
      fragChange: "20%",
      recoil: "",
      effDist: "367",
      maxHsDist: "189",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "4.6x30 mm",
    },
    {
      name: "AP SX",
      damage: "35",
      penValue: "53",
      fragChange: "10%",
      recoil: "10",
      effDist: "198",
      maxHsDist: "Never",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "4.6x30 mm",
    },
  ],
  "9x39mm": [
    {
      name: "SP5",
      damage: "68",
      penValue: "38",
      fragChange: "20%",
      recoil: "",
      effDist: "1710",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "9x39mm",
    },
    {
      name: "SP6",
      damage: "58",
      penValue: "46",
      fragChange: "10%",
      recoil: "10",
      effDist: "1963",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "9x39mm",
    },
    {
      name: "PAB9",
      damage: "62",
      penValue: "48",
      fragChange: "10%",
      recoil: "10",
      effDist: "1823",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
    },
    {
      name: "SPP",
      damage: "64",
      penValue: "50",
      fragChange: "20%",
      recoil: "20",
      effDist: "887",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
    },
    {
      name: "BP",
      damage: "60",
      penValue: "55",
      fragChange: "10%",
      recoil: "22",
      effDist: "1902",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
    },
  ],
  ".366": [
    {
      name: "Geksa",
      damage: "110",
      penValue: "14",
      fragChange: "45%",
      recoil: "",
      effDist: "484",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".366",
    },
    {
      name: "FMJ",
      damage: "98",
      penValue: "23",
      fragChange: "25%",
      recoil: "10",
      effDist: "363",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".366",
    },
    {
      name: "EKO",
      damage: "73",
      penValue: "30",
      fragChange: "20%",
      recoil: "-15",
      effDist: "184",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
      category: ".366",
    },
    {
      name: "AP",
      damage: "90",
      penValue: "42",
      fragChange: "1%",
      recoil: "35",
      effDist: "633",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: ".366",
    },
  ],
  "5.45x39 mm": [
    {
      name: "SP",
      damage: "68",
      penValue: "11",
      fragChange: "45%",
      recoil: "-15",
      effDist: "364",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "HP",
      damage: "74",
      penValue: "11",
      fragChange: "35%",
      recoil: "5",
      effDist: "368",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "PRS",
      damage: "60",
      penValue: "14",
      fragChange: "30%",
      recoil: "-5",
      effDist: "392",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "US",
      damage: "65",
      penValue: "15",
      fragChange: "10%",
      recoil: "-25",
      effDist: "1689",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "T (Tracer)",
      damage: "57",
      penValue: "20",
      fragChange: "16%",
      recoil: "-5",
      effDist: "331",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "FMJ",
      damage: "56",
      penValue: "21",
      fragChange: "25%",
      recoil: "",
      effDist: "400",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "PS",
      damage: "50",
      penValue: "27",
      fragChange: "40%",
      recoil: "",
      effDist: "352",
      maxHsDist: "466",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "PP",
      damage: "48",
      penValue: "33",
      fragChange: "17%",
      recoil: "",
      effDist: "382",
      maxHsDist: "420",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "0",
      category: "5.45x39 mm",
    },
    {
      name: "BP",
      damage: "49",
      penValue: "35",
      fragChange: "16%",
      recoil: "",
      effDist: "378",
      maxHsDist: "455",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "1",
      category: "5.45x39 mm",
    },
    {
      name: "BT (Tracer)",
      damage: "44",
      penValue: "37",
      fragChange: "16%",
      recoil: "3",
      effDist: "310",
      maxHsDist: "252",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.45x39 mm",
    },
    {
      name: "7n40",
      damage: "52",
      penValue: "44",
      fragChange: "2%",
      recoil: "-20",
      effDist: "388",
      maxHsDist: "633",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "5.45x39 mm",
    },
    {
      name: "BS",
      damage: "40",
      penValue: "51",
      fragChange: "17%",
      recoil: "10",
      effDist: "363",
      maxHsDist: "179",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.45x39 mm",
    },
    {
      name: 'PPBS "Igolnik"',
      damage: "37",
      penValue: "62",
      fragChange: "2%",
      recoil: "15",
      effDist: "430",
      maxHsDist: "85",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "5.45x39 mm",
    },
  ],
  "5.56x45 mm": [
    {
      name: "Warmageddon",
      damage: "85",
      penValue: "3",
      fragChange: "90%",
      recoil: "10",
      effDist: "525",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "HP",
      damage: "75",
      penValue: "9",
      fragChange: "70%",
      recoil: "",
      effDist: "327",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "MK 255 Mod 0",
      damage: "60",
      penValue: "17",
      fragChange: "3%",
      recoil: "",
      effDist: "525",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "Mk318 SOST",
      damage: "67",
      penValue: "20",
      fragChange: "15%",
      recoil: "",
      effDist: "409",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "M856 (Tracer)",
      damage: "55",
      penValue: "23",
      fragChange: "33%",
      recoil: "-2",
      effDist: "358",
      maxHsDist: "975",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "FMJ",
      damage: "52",
      penValue: "24",
      fragChange: "50%",
      recoil: "-5",
      effDist: "399",
      maxHsDist: "618",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "M855",
      damage: "50",
      penValue: "28",
      fragChange: "40%",
      recoil: "",
      effDist: "358",
      maxHsDist: "464",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
      category: "5.56x45 mm",
    },
    {
      name: "M856A1 (Tracer)",
      damage: "51",
      penValue: "37",
      fragChange: "33%",
      recoil: "4",
      effDist: "424",
      maxHsDist: "594",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.56x45 mm",
    },
    {
      name: "M855A1",
      damage: "46",
      penValue: "45",
      fragChange: "34%",
      recoil: "5",
      effDist: "366",
      maxHsDist: "352",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "5.56x45 mm",
    },
    {
      name: "M995",
      damage: "40",
      penValue: "53",
      fragChange: "32%",
      recoil: "8",
      effDist: "325",
      maxHsDist: "149",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.56x45 mm",
    },
    {
      name: "SSA AP",
      damage: "36",
      penValue: "56",
      fragChange: "20%",
      recoil: "6",
      effDist: "325",
      maxHsDist: "29",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.56x45 mm",
    },
  ],
  "7.62x39 mm": [
    {
      name: "HP",
      damage: "87",
      penValue: "15",
      fragChange: "26%",
      recoil: "",
      effDist: "382",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "7.62x39 mm",
    },
    {
      name: "US",
      damage: "56",
      penValue: "29",
      fragChange: "8%",
      recoil: "-30",
      effDist: "1811",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "7.62x39 mm",
    },
    {
      name: "T45M1",
      damage: "62",
      penValue: "30",
      fragChange: "12%",
      recoil: "-6",
      effDist: "314",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "7.62x39 mm",
    },
    {
      name: "PS",
      damage: "57",
      penValue: "32",
      fragChange: "25%",
      recoil: "",
      effDist: "393",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      category: "7.62x39 mm",
    },
    {
      name: "BP",
      damage: "58",
      penValue: "47",
      fragChange: "12%",
      recoil: "5",
      effDist: "387",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "7.62x39 mm",
    },
    {
      name: "MAI AP",
      damage: "47",
      penValue: "58",
      fragChange: "5%",
      recoil: "10",
      effDist: "387",
      maxHsDist: "405",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "7.62x39 mm",
    },
  ],
  ".300 blk": [
    {
      name: "Whisper",
      damage: "90",
      penValue: "14",
      fragChange: "35%",
      recoil: "-5",
      effDist: "490",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "2",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".300 blk",
    },
    {
      name: "VMAX",
      damage: "72",
      penValue: "20",
      fragChange: "25%",
      recoil: "-10",
      effDist: "466",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "3",
      class5: "1",
      class6: "0",
      category: ".300 blk",
    },
    {
      name: "BCP FMJ",
      damage: "60",
      penValue: "29",
      fragChange: "30%",
      recoil: "",
      effDist: "563",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
      category: ".300 blk",
    },
    {
      name: "M62 (Tracer)",
      damage: "54",
      penValue: "34",
      fragChange: "0.2",
      recoil: "5",
      effDist: "1039",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".300 blk",
    },
    {
      name: "AP",
      damage: "51",
      penValue: "45",
      fragChange: "30%",
      recoil: "10",
      effDist: "522",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: ".300 blk",
    },
  ],
  "7.62x51 mm": [
    {
      name: "Ultra Nosler",
      damage: "107",
      penValue: "15",
      fragChange: "70%",
      recoil: "-5",
      effDist: "536",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "7.62x51 mm",
    },
    {
      name: "FMJ",
      damage: "88",
      penValue: "31",
      fragChange: "25%",
      recoil: "-3",
      effDist: "584",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "2",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously BPZ",
      category: "7.62x51 mm",
    },
    {
      name: "SP",
      damage: "60",
      penValue: "36",
      fragChange: "20%",
      recoil: "-5",
      effDist: "543",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "2",
      class6: "0",
      note: "",
      secondNote: "Previously TPZ",
      category: "7.62x51 mm",
    },
    {
      name: "M80",
      damage: "80",
      penValue: "41",
      fragChange: "17%",
      recoil: "",
      effDist: "483",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "7.62x51 mm",
    },
    {
      name: "M62 (Tracer)",
      damage: "79",
      penValue: "44",
      fragChange: "14%",
      recoil: "-5",
      effDist: "462",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      category: "7.62x51 mm",
    },
    {
      name: "M61",
      damage: "70",
      penValue: "64",
      fragChange: "13%",
      recoil: "10",
      effDist: "506",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x51 mm",
    },
    {
      name: "M993",
      damage: "67",
      penValue: "70",
      fragChange: "13%",
      recoil: "8",
      effDist: "445",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x51 mm",
    },
  ],
  "7.62x54R": [
    {
      name: "T-46M (Tracer)",
      damage: "82",
      penValue: "41",
      fragChange: "18%",
      recoil: "-5",
      effDist: "406",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "7.62x54R",
    },
    {
      name: "LPS Gzh",
      damage: "81",
      penValue: "42",
      fragChange: "18%",
      recoil: "",
      effDist: "492",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "7.62x54R",
    },
    {
      name: "PS",
      damage: "86",
      penValue: "45",
      fragChange: "8%",
      recoil: "8",
      effDist: "510",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      note: "",
      secondNote: "Previously 7n1",
      category: "7.62x54R",
    },
    {
      name: "BT (Tracer)",
      damage: "78",
      penValue: "59",
      fragChange: "8%",
      recoil: "-4",
      effDist: "491",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7BT1",
      category: "7.62x54R",
    },
    {
      name: "SNB",
      damage: "75",
      penValue: "62",
      fragChange: "8%",
      recoil: "10",
      effDist: "510",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x54R",
    },
    {
      name: "BS",
      damage: "72",
      penValue: "70",
      fragChange: "8%",
      recoil: "",
      effDist: "597",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7n37",
      category: "7.62x54R",
    },
  ],
  "12.7x55 mm": [
    {
      name: "ps12a",
      damage: "165",
      penValue: "10",
      fragChange: "70%",
      recoil: "-12",
      effDist: "439",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12.7x55 mm",
    },
    {
      name: "ps12",
      damage: "115",
      penValue: "28",
      fragChange: "30%",
      recoil: "",
      effDist: "2076",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "1",
      class6: "0",
      category: "12.7x55 mm",
    },
    {
      name: "ps12b",
      damage: "102",
      penValue: "46",
      fragChange: "30%",
      recoil: "15",
      effDist: "719",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "12.7x55 mm",
    },
  ],
  ".338 Lapua Magnum": [
    {
      name: "Tac-X",
      damage: "196",
      penValue: "18",
      fragChange: "50%",
      recoil: "5",
      effDist: "716",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".338 Lapua Magnum",
    },
    {
      name: "UPZ",
      damage: "142",
      penValue: "32",
      fragChange: "60%",
      recoil: "",
      effDist: "702",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".338 Lapua Magnum",
    },
    {
      name: "FMJ",
      damage: "122",
      penValue: "47",
      fragChange: "20%",
      recoil: "",
      effDist: "733",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      category: ".338 Lapua Magnum",
    },
    {
      name: "AP",
      damage: "115",
      penValue: "79",
      fragChange: "13%",
      recoil: "10",
      effDist: "696",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: ".338 Lapua Magnum",
    },
  ],
  "Mounted Weapons": [
    {
      name: "30mm Grenade",
      damage: "199",
      penValue: "1",
      fragChange: "0%",
      recoil: "",
      effDist: "",
      maxHsDist: "",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "This has an explosion radius like grenades which does most (all) of the damage",
      category: "Mounted Weapons",
    },
    {
      name: "12.7x108mm",
      damage: "182",
      penValue: "88",
      fragChange: "17%",
      recoil: "",
      effDist: "891",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "Mounted Weapons",
    },
    {
      name: "12.7x108mm Tracer",
      damage: "199",
      penValue: "80",
      fragChange: "17%",
      recoil: "",
      effDist: "446",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "Mounted Weapons",
    },
  ],
  Other: [
    {
      name: "40mm Buckshot Grenade",
      damage: "160",
      penValue: "5",
      fragChange: "0%",
      recoil: "",
      effDist: "994",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "15 Pellets",
      category: "Other",
    },
  ],
};

export default fallback;
