const gunsData = {
  guns: [
    {
      name: "Colt M4A1 5.56x45 assault rifle",
      shortName: "M4A1",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "Makarov PM 9x18PM pistol",
      shortName: "PM",
      type: "pistols",
      category: "9x18mm Makarov",
    },
    {
      name: "MP-133 12ga pump-action shotgun",
      shortName: "MP-133",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "SV-98 7.62x54R bolt-action sniper rifle",
      shortName: "SV-98",
      type: "sniper rifles",
      category: "7.62x54mmR",
    },
    {
      name: "MP-43-1C 12ga double-barrel shotgun",
      shortName: "MP-43-1C",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "Kalashnikov AK-74N 5.45x39 assault rifle",
      shortName: "AK-74N",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "SIG P226R 9x19 pistol",
      shortName: "P226R",
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "MP-153 12ga semi-automatic shotgun",
      shortName: "MP-153",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "PB 9x18PM silenced pistol",
      shortName: "PB",
      type: "pistol",
      category: "9x18mm Makarov",
    },
    {
      name: "TT-33 7.62x25 TT pistol",
      shortName: "TT",
      type: "pistols",
      category: "7.62x25mm Tokarev",
    },
    {
      name: "Simonov SKS 7.62x39 carbine",
      shortName: "SKS",
      type: "assault carbines",
      category: "7.62x39mm",
    },
    {
      name: "Saiga 12ga ver.10 12/76 semi-automatic shotgun",
      shortName: "Saiga-12",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: 'Yarygin MP-443 "Grach" 9x19 pistol',
      shortName: 'MP-443 "Grach"',
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "VSS Vintorez 9x39 special sniper rifle",
      shortName: "VSS Vintorez",
      type: "designated marksman rifles",
      category: "9x39mm",
    },
    {
      name: "Makarov PM (t) 9x18PM pistol",
      shortName: "PM (t)",
      type: "pistol",
      category: "9x18mm Makarov",
    },
    {
      name: "AS VAL 9x39 special assault rifle",
      shortName: "AS VAL",
      type: "assault carbines",
      category: "9x39mm",
    },
    {
      name: 'PP-91 "Kedr" 9x18PM submachine gun',
      shortName: 'PP-91 "Kedr"',
      type: "submachine guns",
      category: "9x18mm Makarov",
    },
    {
      name: "Kalashnikov AKS-74U 5.45x39 assault rifle",
      shortName: "AKS-74U",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: 'PP-91-01 "Kedr-B" 9x18PM submachine gun',
      shortName: 'PP-91-01 "Kedr-B"',
      type: "submachine guns",
      category: "9x18mm Makarov",
    },
    {
      name: 'PP-9 "Klin" 9x18PMM submachine gun',
      shortName: 'PP-9 "Klin"',
      type: "submachine guns",
      category: "9x18mm Makarov",
    },
    {
      name: "Kalashnikov AKS-74UN 5.45x39 assault rifle",
      shortName: "AKS-74UN",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Kalashnikov AKS-74UB 5.45x39 assault rifle",
      shortName: "AKS-74UB",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Simonov OP-SKS 7.62x39 carbine (Hunting Rifle Version)",
      shortName: "OP-SKS",
      type: "assault carbines",
      category: "7.62x39mm",
    },
    {
      name: "LOBAEV Arms DVL-10 Saboteur 7.62x51 bolt-action sniper rifle",
      shortName: "DVL-10",
      type: "sniper rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "SIG MPX 9x19 submachine gun",
      shortName: "MPX",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "HK MP5 9x19 submachine gun (Navy 3 Round Burst)",
      shortName: "MP5",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: 'PP-19-01 "Vityaz" 9x19 submachine gun',
      shortName: "PP-19-01",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "Kalashnikov AKM 7.62x39 assault rifle",
      shortName: "AKM",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: 'Molot VPO-136 "Vepr-KM" 7.62x39 carbine',
      shortName: 'VPO-136 "Vepr-KM"',
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "Molot VPO-209 .366 TKM carbine",
      shortName: "VPO-209",
      type: "assault rifles",
      category: ".366 TKM",
    },
    {
      name: "Serdyukov SR-1MP Gyurza 9x21 pistol",
      shortName: "SR-1MP",
      type: "pistols",
      category: "9x21mm Gyurza",
    },
    {
      name: "Saiga-9 9x19 carbine",
      shortName: "Saiga-9",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "Kalashnikov AKMS 7.62x39 assault rifle",
      shortName: "AKMS",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "Kalashnikov AKMN 7.62x39 assault rifle",
      shortName: "AKMN",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "Stechkin APS 9x18PM machine pistol",
      shortName: "APS",
      type: "pistol",
      category: "9x18mm Makarov",
    },
    {
      name: "Remington R11 RSASS 7.62x51 marksman rifle",
      shortName: "RSASS",
      type: "designated marksman rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "TOZ-106 20ga bolt-action shotgun",
      shortName: "TOZ-106",
      type: "shotguns",
      category: "20x70mm",
    },
    {
      name: "Remington Model 870 12ga pump-action shotgun",
      shortName: "M870",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "Glock 17 9x19 pistol",
      shortName: "Glock 17",
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "Springfield Armory M1A 7.62x51 rifle",
      shortName: "M1A",
      type: "designated marksman rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "Kalashnikov AKS-74N 5.45x39 assault rifle",
      shortName: "AKS-74N",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Kalashnikov AKMSN 7.62x39 assault rifle",
      shortName: "AKMSN",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "APB 9x18PM silenced machine pistol",
      shortName: "APB",
      type: "pistol",
      category: "9x18mm Makarov",
    },
    {
      name: "Kalashnikov AK-74M 5.45x39 assault rifle",
      shortName: "AK-74M",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Kalashnikov AK-101 5.56x45 assault rifle",
      shortName: "AK-101",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "Kalashnikov AK-102 5.56x45 assault rifle",
      shortName: "AK-102",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "Kalashnikov AK-103 7.62x39 assault rifle",
      shortName: "AK-103",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "Kalashnikov AK-104 7.62x39 assault rifle",
      shortName: "AK-104",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "Kalashnikov AK-105 5.45x39 assault rifle",
      shortName: "AK-105",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Mosin 7.62x54R bolt-action rifle (Sniper)",
      shortName: "Mosin (Sniper)",
      type: "sniper rifles",
      category: "7.62x54mmR",
    },
    {
      name: "DS Arms SA-58 7.62x51 assault rifle",
      shortName: "SA-58",
      type: "assault rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "Glock 18C 9x19 machine pistol",
      shortName: "Glock 18C",
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "TT-33 7.62x25 TT pistol (Golden)",
      shortName: "TT Gold",
      type: "pistols",
      category: "7.62x25mm Tokarev",
    },
    {
      name: "HK MP7A1 4.6x30 submachine gun",
      shortName: "MP7A1",
      type: "submachine guns",
      category: "4.6x30mm HK",
    },
    {
      name: "HK 416A5 5.56x45 assault rifle",
      shortName: "HK 416A5",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "HK MP7A2 4.6x30 submachine gun",
      shortName: "MP7A2",
      type: "submachine guns",
      category: "4.6x30mm HK",
    },
    {
      name: "RPK-16 5.45x39 light machine gun",
      shortName: "RPK-16",
      type: "light machine guns",
      category: "5.45x39mm",
    },
    {
      name: "Kalashnikov AK-74 5.45x39 assault rifle",
      shortName: "AK-74",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Kalashnikov AKS-74 5.45x39 assault rifle",
      shortName: "AKS-74",
      type: "assault rifles",
      category: "5.45x39mm",
    },
    {
      name: "Mosin 7.62x54R bolt-action rifle (Infantry)",
      shortName: "Mosin (Infantry)",
      type: "sniper rifles",
      category: "7.62x54mmR",
    },
    {
      name: "Remington Model 700 7.62x51 bolt-action sniper rifle",
      shortName: "M700",
      type: "sniper rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "ADAR 2-15 5.56x45 carbine",
      shortName: "ADAR 2-15",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "SVDS 7.62x54R sniper rifle",
      shortName: "SVDS",
      type: "designated marksman rifles",
      category: "7.62x54mmR",
    },
    {
      name: "Desert Tech MDR 5.56x45 assault rifle",
      shortName: "MDR",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: 'VPO-101 "Vepr-Hunter" 7.62x51 carbine',
      shortName: 'VPO-101 "Vepr-Hunter"',
      type: "assault carbines",
      category: "7.62x51mm NATO",
    },
    {
      name: "Beretta M9A3 9x19 pistol",
      shortName: "M9A3",
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "ASh-12 12.7x55 assault rifle",
      shortName: "ASh-12",
      type: "assault rifles",
      category: "12.7x55mm STs-130",
    },
    {
      name: "FN P90 5.7x28 submachine gun",
      shortName: "P90",
      type: "submachine guns",
      category: "5.7x28mm FN",
    },
    {
      name: "HK MP5K 9x19 submachine gun",
      shortName: "MP5K-N",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "FN Five-seveN MK2 5.7x28 pistol",
      shortName: "FN 5-7",
      type: "pistols",
      category: "5.7x28mm FN",
    },
    {
      name: "Lone Star TX-15 DML 5.56x45 carbine",
      shortName: "TX-15 DML",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "FN Five-seveN MK2 5.7x28 pistol (FDE)",
      shortName: "FN 5-7 FDE",
      type: "pistols",
      category: "5.7x28mm FN",
    },
    {
      name: "Desert Tech MDR 7.62x51 assault rifle",
      shortName: "MDR",
      type: "assault rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: 'Molot VPO-215 "Gornostay" .366 TKM bolt-action rifle',
      shortName: 'VPO-215 "Gornostay"',
      type: "sniper rifles",
      category: ".366 TKM",
    },
    {
      name: "B&T MP9-N 9x19 submachine gun",
      shortName: "MP9-N",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "ORSIS T-5000M 7.62x51 bolt-action sniper rifle",
      shortName: "T-5000M",
      type: "sniper rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "Knight's Armament Company SR-25 7.62x51 marksman rifle",
      shortName: "SR-25",
      type: "designated marksman rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "B&T MP9 9x19 submachine gun",
      shortName: "MP9",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "Colt M1911A1 .45 ACP pistol",
      shortName: "M1911A1",
      type: "pistols",
      category: ".45 ACP",
    },
    {
      name: "FN40GL Mk2 grenade launcher",
      shortName: "FN40GL",
      type: "grenade launchers",
      category: "40x46 mm",
    },
    {
      name: "TOZ KS-23M 23x75mm pump-action shotgun",
      shortName: "KS-23M",
      type: "shotguns",
      category: "23x75mm",
    },
    {
      name: "Mossberg 590A1 12ga pump-action shotgun",
      shortName: "590A1",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "PPSh-41 7.62x25 submachine gun",
      shortName: "PPSh41",
      type: "submachine guns",
      category: "7.62x25mm Tokarev",
    },
    {
      name: "Kel-Tec RFB 7.62x51 rifle",
      shortName: "RFB",
      type: "assault carbines",
      category: "7.62x51mm NATO",
    },
    {
      name: "Colt M45A1 .45 ACP pistol",
      shortName: "M45A1",
      type: "pistols",
      category: ".45 ACP",
    },
    {
      name: "TDI KRISS Vector Gen.2 .45 ACP submachine gun",
      shortName: "Vector .45ACP",
      type: "submachine guns",
      category: ".45 ACP",
    },
    {
      name: "SIG MCX .300 Blackout assault rifle",
      shortName: "MCX .300 BLK",
      type: "assault rifles",
      category: ".300 Blackout",
    },
    {
      name: "SWORD International Mk-18 .338 LM marksman rifle",
      shortName: "Mk-18",
      type: "designated marksman rifles",
      category: ".338 Lapua Magnum",
    },
    {
      name: "HK UMP .45 ACP submachine gun",
      shortName: "UMP 45",
      type: "submachine guns",
      category: ".45 ACP",
    },
    {
      name: "TDI KRISS Vector Gen.2 9x19 submachine gun",
      shortName: "Vector 9x19",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "PL-15 9x19 pistol",
      shortName: "PL-15",
      type: "pistols",
      category: "9x19mm Parabellum",
    },
    {
      name: "Soyuz-TM STM-9 Gen.2 9x19 carbine",
      shortName: "STM-9",
      type: "submachine guns",
      category: "9x19mm Parabellum",
    },
    {
      name: "CMMG Mk47 Mutant 7.62x39 assault rifle",
      shortName: "Mk47",
      type: "assault rifles",
      category: "7.62x39mm",
    },
    {
      name: "MP-155 12ga semi-automatic shotgun",
      shortName: "MP-155",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "MTs-255-12 12ga shotgun",
      shortName: "MTs-255-12",
      type: "shotguns",
      category: "12x70mm",
    },
    {
      name: "FN SCAR-H 7.62x51 assault rifle (FDE)",
      shortName: "Mk 17",
      type: "assault rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "HK G28 7.62x51 marksman rifle",
      shortName: "G28",
      type: "designated marksman rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "FN SCAR-H 7.62x51 assault rifle",
      shortName: "Mk 17",
      type: "assault rifles",
      category: "7.62x51mm NATO",
    },
    {
      name: "FN SCAR-L 5.56x45 assault rifle",
      shortName: "Mk 16",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "FN SCAR-L 5.56x45 assault rifle (FDE)",
      shortName: "Mk 16",
      type: "assault rifles",
      category: "5.56x45mm NATO",
    },
    {
      name: "HK USP .45 ACP pistol",
      shortName: "USP .45",
      type: "pistols",
      category: ".45 ACP",
    },
  ],
  categoriesMapping: {
    "12 Gauge Shot": "12x70mm",
    "12 Gauge Slugs": "12x70mm",
    "20 Gauge": "20x70mm",
    "23x75 mm": "23x75mm",
    "9x18mm": "9x18mm Makarov",
    "7.62x25mm": "7.62x25mm Tokarev",
    "9x19mm": "9x19mm Parabellum",
    ".45": ".45 ACP",
    "9x21mm": "9x21mm Gyurza",
    "5.7x28 mm": "5.7x28mm FN",
    "4.6x30 mm": "4.6x30mm HK",
    "9x39mm": "9x39mm",
    ".366": ".366 TKM",
    "5.45x39 mm": "5.45x39mm",
    "5.56x45 mm": "5.56x45mm NATO",
    "7.62x39 mm": "7.62x39mm",
    ".300 blk": ".300 Blackout",
    "7.62x51 mm": "7.62x51mm NATO",
    "7.62x54R": "7.62x54mmR",
    "12.7x55 mm": "12.7x55mm STs-130",
    ".338 Lapua Magnum": ".338 Lapua Magnum",
    Other: "40x46 mm",
  },
};

export default gunsData;
